# Values use GVariant syntax. Only these keys are managed.
[org.gnome.desktop.interface]
color-scheme = 'prefer-dark'

[org.gnome.desktop.wm.preferences]
button-layout = 'close,minimize,maximize:'

[org.gnome.shell.keybindings]
show-screenshot-ui = ['Print', '<Super><Shift>5']

[org.gnome.desktop.wm.keybindings]
activate-window-menu = []

[org.gnome.shell.extensions.dash-to-dock]
dock-position = 'BOTTOM'
dock-fixed = false
autohide = true
intellihide = true
dash-max-icon-size = 48
extend-height = false
hot-keys = true
app-shift-hotkey-1 = []
app-shift-hotkey-2 = []
app-shift-hotkey-3 = []
app-shift-hotkey-4 = []
app-shift-hotkey-5 = []
app-shift-hotkey-6 = []
app-shift-hotkey-7 = []
app-shift-hotkey-8 = []
app-shift-hotkey-9 = []
app-shift-hotkey-10 = []

[org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vicinae/]
name = 'Vicinae'
command = '/usr/bin/vicinae toggle'
binding = '<Alt>space'
