# Values use GVariant syntax. Only these keys are managed.
[org.gnome.desktop.interface]
color-scheme = 'prefer-dark'
icon-theme = 'WhiteSur'

[org.gnome.desktop.wm.preferences]
button-layout = 'close,minimize,maximize:'

[org.gnome.shell.keybindings]
show-screenshot-ui = ['Print', '<Super><Shift>5']

[org.gnome.desktop.wm.keybindings]
activate-window-menu = []

[org.gnome.shell.extensions.dash-to-dock]
dock-position = 'BOTTOM'
dock-fixed = false
autohide = true
intellihide = true
dash-max-icon-size = 48
extend-height = false
hot-keys = true
app-shift-hotkey-1 = []
app-shift-hotkey-2 = []
app-shift-hotkey-3 = []
app-shift-hotkey-4 = []
app-shift-hotkey-5 = []
app-shift-hotkey-6 = []
app-shift-hotkey-7 = []
app-shift-hotkey-8 = []
app-shift-hotkey-9 = []
app-shift-hotkey-10 = []

[org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/vicinae/]
name = 'Vicinae'
command = '/usr/bin/vicinae toggle'
binding = '<Alt>space'

[org.gnome.shell.extensions.moe.liam.speedinator]
app-grid-grace-period = 100
speed = 1.3

[org.gnome.shell.extensions.blur-my-shell]
pipelines = {'pipeline_default': {'name': <'Default'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_000000000000'>, 'params': <{'radius': <30>, 'brightness': <0.59999999999999998>, 'unscaled_radius': <30>}>}>]>}, 'pipeline_default_rounded': {'name': <'Default rounded'>, 'effects': <[<{'type': <'native_static_gaussian_blur'>, 'id': <'effect_000000000001'>, 'params': <{'radius': <30>, 'brightness': <0.59999999999999998>}>}>, <{'type': <'corner'>, 'id': <'effect_000000000002'>, 'params': <{'radius': <24>}>}>]>}}
settings-version = 2
sigma = 30
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
noise-amount = 0.0
noise-lightness = 0.0
color-and-noise = true

[org.gnome.shell.extensions.blur-my-shell.appfolder]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
customize = false
noise-amount = 0.0
noise-lightness = 0.0
sigma = 30
style-dialogs = 1

[org.gnome.shell.extensions.blur-my-shell.applications]
blur = false
pipeline = 'pipeline_default'

[org.gnome.shell.extensions.blur-my-shell.coverflow-alt-tab]
blur = true
pipeline = 'pipeline_default'

[org.gnome.shell.extensions.blur-my-shell.dash-to-dock]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
corner-radius = 18
customize = false
noise-amount = 0.0
noise-lightness = 0.0
override-background = true
pipeline = 'pipeline_default_rounded'
sigma = 30
static-blur = false
style-dash-to-dock = 0
unblur-in-overview = false

[org.gnome.shell.extensions.blur-my-shell.dash-to-panel]
blur-original-panel = true

[org.gnome.shell.extensions.blur-my-shell.hidetopbar]
compatibility = false

[org.gnome.shell.extensions.blur-my-shell.lockscreen]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
customize = false
noise-amount = 0.0
noise-lightness = 0.0
pipeline = 'pipeline_default'
sigma = 30

[org.gnome.shell.extensions.blur-my-shell.overview]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
customize = false
noise-amount = 0.0
noise-lightness = 0.0
pipeline = 'pipeline_default'
sigma = 30
style-components = 1

[org.gnome.shell.extensions.blur-my-shell.panel]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
corner-radius = 0
customize = false
force-light-text = false
noise-amount = 0.0
noise-lightness = 0.0
override-background = true
override-background-dynamically = false
pipeline = 'pipeline_default'
sigma = 30
static-blur = true
style-panel = 0
unblur-in-overview = true

[org.gnome.shell.extensions.blur-my-shell.screenshot]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
customize = false
noise-amount = 0.0
noise-lightness = 0.0
pipeline = 'pipeline_default'
sigma = 30

[org.gnome.shell.extensions.blur-my-shell.window-list]
blur = true
brightness = 0.59999999999999998
color = (0.0, 0.0, 0.0, 0.0)
customize = false
noise-amount = 0.0
noise-lightness = 0.0
pipeline = 'pipeline_default'
sigma = 30
